name: client_server_socket_encrypt
description: A command line basic client-server using sockets in dart. Encryption has been included in option.
version: 0.0.1
repository: https://github.com/Adevenn/client_server_socket_encrypt.git

environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.4.2
  asn1lib: ^1.5.0
  encrypt: ^5.0.3
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0